version: 2.1

orbs:
  cfa: continuousauth/npm@2.1.1
  node: electronjs/node@2.3.1

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test:
          executor: node/macos
          name: test-mac-<< matrix.node-version >>
          override-ci-command: yarn install --frozen-lockfile
          test-steps:
            - run: yarn lint
            - run: yarn test
          use-test-steps: true
          matrix:
            alias: test-mac
            parameters:
              node-version:
                - '22.13'
      - cfa/release:
          requires:
            - test-mac
          filters:
            branches:
              only:
                - main
          context: cfa-release
