version: 2.1

orbs:
  cfa: continuousauth/npm@1.0.2
  node: electronjs/node@1.4.1

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test:
          executor: node/macos
          name: test-mac-<< matrix.node-version >>
          override-ci-command: yarn install --frozen-lockfile --ignore-engines
          test-steps:
            - run: yarn lint
            - run: yarn test
          use-test-steps: true
          matrix:
            alias: test-mac
            parameters:
              node-version:
                - 20.5.0
                - 18.17.0
                - 16.20.1
                - 14.21.3
                # - 12.22.12
                # - 10.24.1
      - cfa/release:
          requires:
            - test-mac
          filters:
            branches:
              only:
                - main
          context: cfa-release
